# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
python:
  - "3.6"

install:
  - pip install -r requirements-dev.txt

script:
  - doit


jobs:
  include:
    - stage: Test
      script:
        - doit
    - stage: Deploy
      script:
        - python setup.py sdist bdist_wheel
        - twine upload dist/*
      branches:
        only:
          - master